spring:
  application:
    name: gateway

  cloud:
    gateway:
      filter:
        local-response-cache:
          enabled: true

  data:
    redis:
      host: 192.168.1.187
      port: 7007

  datasource:
    url: jdbc:postgresql://192.168.1.187:7006/postgres
    username: p0sTgUS3r
    password: p0StgResQl
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
